// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrmElement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<int>("X")
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasMaxLength(200)
=======
>>>>>>> 3e3e200 (Drag & drop WIP.)
=======
>>>>>>> 3e3e20054a93f0369771e5a8ddd4c109efb1b5d2
                        .HasColumnType("integer")
                        .HasColumnName("x_coordinate");

                    b.Property<int>("Y")
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasMaxLength(200)
=======
>>>>>>> 3e3e200 (Drag & drop WIP.)
=======
>>>>>>> 3e3e20054a93f0369771e5a8ddd4c109efb1b5d2
                        .HasColumnType("integer")
                        .HasColumnName("y_coordinate");

                    b.HasKey("Id");

<<<<<<< HEAD
<<<<<<< HEAD
                    b.ToTable("users", (string)null);
=======
                    b.ToTable("crm_elements", (string)null);
>>>>>>> 3e3e200 (Drag & drop WIP.)
=======
                    b.ToTable("crm_elements", (string)null);
>>>>>>> 3e3e20054a93f0369771e5a8ddd4c109efb1b5d2
                });
#pragma warning restore 612, 618
        }
    }
}
